### ISSUE TITLE
Already used by contao 4

### ISSUE THREAD

**Issue by agoat** [contao/image#17]
Sorry, if I abuse this for a question.

Is this library already used by contao 4?

I try to rewrite my imageondemand extension for contao 4 and currently searching how to implement it the best way. So I found this library but no informations. If this will be used in contao 4 in the future I want to rely on.

**Comment by ausi** [comment]
It will be most likely in Contao 4.3 as it was merged in contao/core-bundle#342. But I cannot guarantee that the integration in Contao doesn’t change until 4.3.0 is released.

**Comment by ausi** [comment]
As [Contao 4.3.0](https://github.com/contao/core-bundle/releases/tag/4.3.0) was released today, this library is now used in the latest Contao version.
