### ISSUE TITLE
Save progressive JPEGs

### ISSUE THREAD

**Issue by ausi** [contao/image#24]
We should use [`Imagine\Image\ImageInterface::interlace()`](https://github.com/avalanche123/Imagine/blob/68d416ee2be3423c5758bddd31be11fcd80d16e5/lib/Imagine/Image/ImageInterface.php#L127) to store the JPEG files as progressive images.

This should most likely be configurable.

**Comment by ausi** [comment]
From <https://www.imagemagick.org/script/command-line-options.php#interlace>:

> Use `Line` or `Plane` to create an `interlaced PNG` or `GIF` or `progressive JPEG` image.

And <http://stackoverflow.com/questions/7261855/recommendation-for-compressing-jpg-files-with-imagemagick>:

> `convert -strip -interlace Plane -gaussian-blur 0.05 -quality 85% source.jpg result.jpg`

Looks like `ImageInterface::INTERLACE_PLANE` is the way to go.

**Comment by leofeyer** [comment]
Any setting but `INTERLACE_NONE` should get us a progressive JPG:

http://stackoverflow.com/questions/36424677/whats-the-practical-differences-between-imagickinterlace-jpeg-interlace-plane

But I also think that `INTERLACE_PLANE` is the way to go.

**Comment by ausi** [comment]
Implemented in c70dbc4ab8d26288d6a837545785730ea4b973f9.

Progressive JPEGs can now be generated by using the Imagine option `'interlace' => \Imagine\Image\ImageInterface::INTERLACE_PLANE`.
