### ISSUE TITLE
Add compatibility with imagine 0.7

### ISSUE THREAD

**Issue by ausi** [contao/image#35]
A new version of imagine/imagine [got released](https://github.com/avalanche123/Imagine/releases/tag/v0.7.0). 

Check the compatibility and update composer.json to:

```json
"imagine/imagine": "^0.6|^0.7",
```

**Comment by leofeyer** [comment]
I have no idea what to check actually. 😄 

https://github.com/avalanche123/Imagine/commits/v0.7.0
