### ISSUE TITLE
Image attributes partial override

### ISSUE THREAD

**Issue by FuturaDink** [contao/image#43]
Is it possible to override only one of the needed attributes (set in the "Dateiverwaltung", var = _default_image_meta_) in the image ("Metadaten überschreiben")?
I suggest to show _default_image_meta_ every time "Metadaten überschreiben" is needed.

**Comment by ausi** [comment]
I don’t think this issue is related to the `contao/image` library.

Please refer to the [Community Forum](https://community.contao.org/) for questions or open an issue in [contao/core-bundle](https://github.com/contao/core-bundle) for feature requests.
