### ISSUE TITLE
Improve security of image filenames

### ISSUE THREAD

**Issue by ausi** [contao/image#87]
The paths for resized versions of private images should not be guessable for security reasons.

See [contao/contao@`9c517c7` (#3848)](https://github.com/contao/contao/pull/3848/commits/9c517c77e944a1260c4a3bbe6942327f7e0357d4)

**Comment by ausi** [comment]
Idea for better backwards compatibility:

Still calculate the old hash, and if the resized image already exists with the old name, return it. But if it does not exist, create a new image with the new hash algorithm instead.

**Comment by leofeyer** [comment]
Do we need backwards compatibility? We could also ask the users to rebuild their cache.

**Comment by ausi** [comment]
> We could also ask the users to rebuild their cache.

This can be a very huge number of images that have to be regenerated. If the backwards compatibililty can be achieved without too much effort I would favor it.

**Comment by ausi** [comment]
Closed in favor of #90
